### ISSUE TITLE
CI and packrat

### ISSUE THREAD

**Issue by benmarwick** [jhollist/manuscriptPackage#2]
This looks great and I'm curious to see how you'd include continuous integration and packrat. 

I had a go with myarticle-package here: https://github.com/benmarwick/Stratigraphy-and-radiocarbon-dates-from-Gua-Mo-o-hono-Sulawesi 

But I'd love to see how someone who knows what they're doing does it!

**Comment by jhollist** [comment]
@benmarwick closing this just to clean some stuff up.  It is still an open issue I agree, but not likely to be solved here!
