### ISSUE TITLE
disabling date printing at page bottom

### ISSUE THREAD

**Issue by Pakillo** [jhollist/manuscriptPackage#4]
Hi @jhollist ,

Thanks again for the template. I wonder if you can quickly point me to how to disable printing of the date at the bottom of the page. I have been trying different changes in the manuscript.latex template without success (my knowledge of LaTeX is very limited).

No worries if you can't answer! Thanks

**Comment by jhollist** [comment]
@Pakillo 

My knowledge of LaTeX has come entirely from working on this, so minimal at best!!!

That being said, the date comes from \rfoot{}.  I just added a YAML switch to manuscript.Rmd and the control is on lines 168-170 of components/manuscript.latex.  That has been pushed up to mansucriptPackage.

And thanks again for including this in [rmdTemplates](https://github.com/Pakillo/rmdTemplates)!

**Comment by Pakillo** [comment]
Awesome, thanks a lot!
